### ISSUE TITLE
Fatal signal 6 (SIGABRT) at 0x000046bb (code=-6), thread 18107 

### ISSUE THREAD

**Issue by VivekMsys** [gotev/pjsip-android#1]
JNI WARNING: NewStringUTF input is not valid Modified UTF-8: illegal continuation byte 0xed
1 W/dalvikvm:              string: '2000t��h��i��h��i�p)c,�i�p)c̩i8'
 W/dalvikvm:              in Lorg/pjsip/pjsua2/pjsua2JNI;.OnInstantMessageParam_msgBody_get:(JLorg/pjsip/pjsua2/OnInstantMessageParam;)Ljava/lang/String; (NewStringUTF)

**Comment by gotev** [comment]
not reproducible with latest release
